# Generated by Django 3.2.7 on 2022-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_slider_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ImageField(upload_to='')),
                ('month', models.CharField(max_length=20)),
                ('news_pic', models.ImageField(default='', upload_to='news_pic')),
                ('news_desc', models.TextField()),
            ],
        ),
    ]
