# Generated by Django 3.2.7 on 2022-03-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='day',
            field=models.IntegerField(),
        ),
    ]
