# Generated by Django 3.2.7 on 2022-03-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_news_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Best News About Rainfall in India', max_length=200),
        ),
    ]
