# Generated by Django 3.2.7 on 2022-03-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='Jan_Feb',
            field=models.FloatField(db_column='Jan-Feb', default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='Jun_Sep',
            field=models.FloatField(db_column='Jun-Sep', default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='Mar_May',
            field=models.FloatField(db_column='Mar-May', default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='Oct_Dec',
            field=models.FloatField(db_column='Oct-Dec', default=0),
        ),
    ]
